name: Tests
on: [pull_request]
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install Poetry
      run: |
        python -m pip install poetry
    - name: Fix pyproject.toml
      run: |
        # pyproject.toml에서 author 정보 수정
        if [ -f pyproject.toml ]; then
          sed -i 's/authors = \[.*\]/authors = ["Danny Park <danny@example.com>"]/' pyproject.toml
          # poetry.lock 파일 재생성 (--no-update 옵션 제거)
          poetry lock
        fi
    - name: Install dependencies
      run: |
        poetry install
    - name: Publish
      run: bash scripts/lint-test.sh
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 8
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: |
        python -m pip install poetry
    - name: Fix pyproject.toml
      run: |
        # pyproject.toml에서 author 정보 수정
        if [ -f pyproject.toml ]; then
          sed -i 's/authors = \[.*\]/authors = ["Danny Park <danny@example.com>"]/' pyproject.toml
          # poetry.lock 파일 재생성 (--no-update 옵션 제거)
          poetry lock
        fi
    - name: Install dependencies
      run: |
        poetry install
    - name: Test
      run: |
        poetry run pytest --cov=rcs_pydantic tests/ --cov-report=xml
    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.xml
        fail_ci_if_error: false
        verbose: true